<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net10.0-windows</TargetFramework>
		<UseWPF>true</UseWPF>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Prism.Wpf" Version="9.0.537" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\..\Core\MarcusRunge.Mopr.Workbench.Core.csproj" />
		<ProjectReference Include="..\..\Services\Application\MarcusRunge.Mopr.Workbench.Services.Application.csproj" />
	</ItemGroup>

	<ItemGroup>
		<Compile Update="Properties\Resources.Designer.cs">
			<DesignTime>True</DesignTime>
			<AutoGen>True</AutoGen>
			<DependentUpon>Resources.resx</DependentUpon>
		</Compile>
	</ItemGroup>

	<ItemGroup>
		<EmbeddedResource Update="Properties\Resources.resx">
			<Generator>PublicResXFileCodeGenerator</Generator>
			<LastGenOutput>Resources.Designer.cs</LastGenOutput>
		</EmbeddedResource>

		<EmbeddedResource Update="Properties\Resources.de.resx">
			<Generator />
		</EmbeddedResource>
	</ItemGroup>

</Project>