<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <ApplicationIcon>Assets\mopr.ico</ApplicationIcon>
    <PackageIcon>mopr.png</PackageIcon>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <Compile Remove="Services\**" />
    <EmbeddedResource Remove="Services\**" />
    <None Remove="Services\**" />
    <Page Remove="Services\**" />
  </ItemGroup>
  <ItemGroup>
    <Content Include="Assets\mopr.ico">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Prism.DryIoc" Version="9.0.537" />
    <PackageReference Include="System.Reactive" Version="7.0.0" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Services\Miras\MarcusRunge.Mopr.Workbench.Services.Miras.csproj" />
    <ProjectReference Include="..\Services\Persistence\MarcusRunge.Mopr.Workbench.Services.Persistence.csproj" />
    <ProjectReference Include="..\Core\MarcusRunge.Mopr.Workbench.Core.csproj" />
    <ProjectReference Include="..\Modules\Imaging\MarcusRunge.Mopr.Workbench.Modules.Imaging.csproj" />
    <ProjectReference Include="..\Services\Core\MarcusRunge.Mopr.Workbench.Services.Core.csproj" />
    <ProjectReference Include="..\Services\Dicom\MarcusRunge.Mopr.Workbench.Services.Dicom.csproj" />
    <ProjectReference Include="..\Services\Repository\MarcusRunge.Mopr.Workbench.Services.Repository.csproj" />
    <ProjectReference Include="..\Services\Wpf\MarcusRunge.Mopr.Workbench.Services.Wpf.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Compile Update="Properties\Resources.de.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Resources.de.resx</DependentUpon>
    </Compile>
    <Compile Update="Properties\Resources.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Resources.resx</DependentUpon>
    </Compile>
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Update="Properties\Resources.de.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>Resources.de.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <EmbeddedResource Update="Properties\Resources.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>Resources.Designer.cs</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>
  <ItemGroup>
    <None Update="Assets\mopr.png">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup></Project>