<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFramework>net10.0-windows</TargetFramework>
		<UseWPF>true</UseWPF>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<IsPackable>false</IsPackable>
		<IsTestProject>true</IsTestProject>
		<RootNamespace>MarcusRunge.Mopr.Workbench.Modules.Miras.Test</RootNamespace>
		<AssemblyName>MarcusRunge.Mopr.Workbench.Modules.Miras.Test</AssemblyName>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.10.1" />
		<PackageReference Include="Moq" Version="4.21.0" />
		<PackageReference Include="xunit.v3" Version="4.0.1" />
		<PackageReference Include="xunit.runner.visualstudio" Version="4.0.0">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\..\Contracts\MarcusRunge.Mopr.Workbench.Contracts.csproj" />
		<ProjectReference Include="..\..\Core\MarcusRunge.Mopr.Workbench.Core.csproj" />
		<ProjectReference Include="..\..\Modules\Miras\MarcusRunge.Mopr.Workbench.Modules.Miras.csproj" />
		<ProjectReference Include="..\..\Services\Application\MarcusRunge.Mopr.Workbench.Services.Application.csproj" />
		<ProjectReference Include="..\..\Services\Miras\MarcusRunge.Mopr.Workbench.Services.Miras.csproj" />
		<ProjectReference Include="..\Test.Shared\MarcusRunge.Mopr.Workbench.Test.Shared.csproj" />
	</ItemGroup>
</Project>