<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Prism.DryIoc" Version="9.0.537" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Mopr.Workbench.Core\Mopr.Workbench.Core.csproj" />
    <ProjectReference Include="..\Modules\Mopr.Workbench.Modules.ModuleName\Mopr.Workbench.Modules.ModuleName.csproj" />
    <ProjectReference Include="..\Services\Mopr.Workbench.Services.Interfaces\Mopr.Workbench.Services.Interfaces.csproj" />
    <ProjectReference Include="..\Services\Mopr.Workbench.Services\Mopr.Workbench.Services.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Compile Update="Properties\Resources.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Resources.resx</DependentUpon>
    </Compile>
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Update="Properties\Resources.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>Resources.Designer.cs</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>
</Project>