<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <ApplicationIcon>Assets\mopr.ico</ApplicationIcon>
    <PackageIcon>mopr.png</PackageIcon>
  </PropertyGroup>
  <ItemGroup>
    <Content Include="Assets\mopr.ico">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Prism.DryIoc" Version="9.0.537" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\MarcusRunge.Mopr.Workbench.Services.Core\MarcusRunge.Mopr.Workbench.Services.Core.csproj" />
    <ProjectReference Include="..\MarcusRunge.Mopr.Workbench.Core\MarcusRunge.Mopr.Workbench.Core.csproj" />
    <ProjectReference Include="..\Modules\MarcusRunge.Mopr.Workbench.Modules.Imaging\MarcusRunge.Mopr.Workbench.Modules.Imaging.csproj" />
    <ProjectReference Include="..\Services\MarcusRunge.Mopr.Workbench.Services.Interfaces\MarcusRunge.Mopr.Workbench.Services.Interfaces.csproj" />
    <ProjectReference Include="..\Services\MarcusRunge.Mopr.Workbench.Services\MarcusRunge.Mopr.Workbench.Services.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Compile Update="Properties\Resources-de.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Resources-de.resx</DependentUpon>
    </Compile>
    <Compile Update="Properties\Resources.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Resources.resx</DependentUpon>
    </Compile>
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Update="Properties\Resources-de.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>Resources-de.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <EmbeddedResource Update="Properties\Resources.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>Resources.Designer.cs</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>
  <ItemGroup>
    <None Update="Assets\mopr.png">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>
  <ItemGroup>
    <Folder Include="Services\Dialog\" />
  </ItemGroup></Project>