<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Prism.Wpf" Version="9.0.537" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\MarcusRunge.Mopr.Workbench.Core\MarcusRunge.Mopr.Workbench.Core.csproj" />
    <ProjectReference Include="..\..\Services\MarcusRunge.Mopr.Workbench.Services.Core\MarcusRunge.Mopr.Workbench.Services.Core.csproj" />
    <ProjectReference Include="..\..\Services\MarcusRunge.Mopr.Workbench.Services.Wpf\MarcusRunge.Mopr.Workbench.Services.Wpf.csproj" />
  </ItemGroup>
</Project>